on: [push, pull_request]
jobs:
  build:
    if: ${{github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)}}
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64, Win32]
        include:
          - arch: x64
            triplet: x64-windows
          - arch: Win32
            triplet: x86-windows

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          cmake -B build-${{matrix.arch}} -A ${{matrix.arch}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON -DVCPKG_TARGET_TRIPLET=${{matrix.triplet}}
          cmake --build build-${{matrix.arch}} --config Release --parallel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{github.event.repository.name}}-${{matrix.arch}}
          path: build-${{matrix.arch}}/Release/*
